[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
evm_version = "prague"
solc_version = "0.8.33"

[profile.deploy]
optimizer_runs = 999999
via_ir = true

[fmt]
sort_imports = true
wrap_comments = true
