[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
optimizer = true
optimizer_runs = 200
evm_version = "prague"
solc_version = "0.8.33"
gas_reports = ["SmartAccount7702"]

[profile.deploy]
evm_version = "prague"
solc_version = "0.8.33"
optimizer_runs = 999999
via_ir = true

[fmt]
sort_imports = true
wrap_comments = true
line_length = 120
number_underscore = "thousands"
